name: ezze_expense
description: EzzeExpense - Personal Expense Tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.68.0

  # File sharing & path
  path_provider: ^2.1.2
  share_plus: ^7.2.2

  # UUID
  uuid: ^4.3.3

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1


  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
